import type { Metadata } from "next";
import Header from '../components/header';
import React from 'react';
import "./globals.css";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode;
}) {
    return (
        <html lang="en">
        <body>
        <Header />
        <main className="min-h-screen text-white">
            {children}
        </main>
        <footer className="py-4 bg-gray-800 text-center text-white">
            <p>&copy; 2024 Your Name. All rights reserved.</p>
        </footer>
        </body>
        </html>
    );
}